server.port=8081
spring.application.name=profile-service
### Database config
spring.datasource.url=jdbc:mysql://localhost:3306/eduShare?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.open-in-view=false
#spring.sql.init.mode=always
springdoc.api-docs.path=/profile/v3/api-docs
springdoc.api-docs.enabled=true
### Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
