package com.example.identityservice.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Getter
@NoArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED ERROR"),
    AUTHENTICATION_FAILED(2000, "AUTHENTICATION FAILED"),
    LOGIN_FAILED(2000, "WRONG USERNAME OR PASSWORD"),
    INVALID_ARGUMENT(2000, "INVALID ARGUMENT"),
    FIRST_NAME_CANT_NULL_OR_EMPTY(2000, "FIRST NAME CANT NULL OR EMPTY"),
    INVALID_LENGTH_FIRSTNAME(2000, "FIRST NAME MUST BE BETWEEN 2 AND 20 CHARACTERS"),
    LAST_NAME_CANT_NULL_OR_EMPTY(2000, "LAST NAME CANT NULL OR EMPTY"),
    INVALID_LENGTH_LASTNAME(2000, "LAST NAME MUST BE BETWEEN 2 AND 20 CHARACTERS"),
    INVALID_LENGTH_EMAIL(2000, "EMAIL MUST BE THAN 2 CHARACTERS"),
    EMAIL_CANT_NULL_OR_EMPTY(2000, "EMAIL CANT NULL OR EMPTY"),
    INVALID_FORMAT_EMAIL(2000, "INVALID FORMAT EMAIL"),
    INVALID_LENGTH_USERNAME(2000, "USERNAME MUST BE BETWEEN 2 AND 20 CHARACTERS"),
    USERNAME_CANT_NULL_OR_EMPTY(2000, "USERNAME CANT NULL OR EMPTY"),
    INVALID_LENGTH_PASSWORD(2000, "PASSWORD MUST BE BETWEEN 8 AND 20 CHARACTERS"),
    PASSWORD_CANT_NULL_OR_EMPTY(2000, "PASSWORD CANT NULL OR EMPTY"),
    ROLE_NOT_FOUND(2000, "ROLE NOT FOUND"),
    USER_EMAIL_EXISTED(20000, "USER EMAIL EXISTED"),
    ACCOUNT_USERNAME_EXISTED(2000, "ACCOUNT USERNAME EXISTED"),
    ACCOUNT_USERNAME_NOT_FOUND(2000, "WRONG ACCOUNT USERNAME OR PASSWORD");

    private int code;
    private String message;
}
